FROM python:3.9.12-slim

ENV MIDDLEWARE_MINIO_SERVICE_HOST=192.168.100.10
ENV MIDDLEWARE_MINIO_SERVICE_PORT=30320
ENV MIDDLEWARE_MINIO_ACCESS_KEY=admin
ENV MIDDLEWARE_MINIO_SECRET_KEY=changeme
ENV BUCKET_NAME=jmx
ENV PREFIX=hpc

WORKDIR /boxter
COPY scripts/init_containers.py /boxter/

RUN pip install minio

CMD ["python","init_containers.py"]