# service for files
---
kind: Service
apiVersion: v1
metadata:
  name: files
  labels:
    app: files
spec:
  selector:
    app: files
  ports:
    - protocol: TCP
      name: http
      port: 8004
      targetPort: 8004
  clusterIP: None

# deployment for files
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: files
  labels:
    app: files
spec:
  replicas: 1
  selector:
    matchLabels:
      app: files
  template:
    metadata:
      labels:
        app: files
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: files
          image: {{ .Values.image }}
          securityContext:
            runAsUser: 0
            privileged: false
          command:
            - "uvicorn"
          args:
            - "src.main:app"
            - "--reload"
            - "--host=0.0.0.0"
            - "--port=8004"
          ports:
            - containerPort: 8004
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          {{- if .Values.allureService }}
          volumeMounts:
            - name: reports-volume
              mountPath: /files/tmp
          {{- end }}
          env:
            - name: MIDDLEWARE_MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: middleware-minio
                  key: root-user
            - name: MIDDLEWARE_MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: middleware-minio
                  key: root-password
      {{- if .Values.allureService }}
      volumes:
        - name: reports-volume
          persistentVolumeClaim:
            claimName: allure-persistent-volume-claim
      {{- end }}


