---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-atop-reports
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage }}
  resources:
    requests:
      storage: 10Gi
