# ---
# kind: Service
# apiVersion: v1
# metadata:
#   name: "{{ .Release.Name }}-{{ .Chart.Name }}"
#   labels:
#     app: "{{ .Release.Name }}-{{ .Chart.Name }}"
# spec:
#   selector:
#     app: "{{ .Release.Name }}-{{ .Chart.Name }}"
#   ports:
#     - protocol: TCP
#       name: http
#       port: 8006
#       targetPort: 8000
#     - protocol: TCP
#       name: files
#       port: 8400
#       targetPort: 8400

# ---
# apiVersion: apps/v1
# kind: StatefulSet
# metadata:
#   name: "{{ .Release.Name }}-{{ .Chart.Name }}"
# spec:
#   selector:
#     matchLabels:
#       app: "{{ .Release.Name }}-{{ .Chart.Name }}"
#   serviceName: "{{ .Release.Name }}-{{ .Chart.Name }}"
#   replicas: 3
#   template:
#     metadata:
#       labels:
#         app: "{{ .Release.Name }}-{{ .Chart.Name }}"
#     spec:
#       imagePullSecrets:
#         - name: regcred
#       containers:
#         - name: files
#           image: "{{ .Values.registry }}/{{ .Values.repository }}/{{ .Values.image }}"
#           securityContext:
#             runAsUser: 0
#             privileged: false
#           command:
#             - "uvicorn"
#           args:
#             - "src.main:app"
#             - "--reload"
#             - "--host=0.0.0.0"
#             - "--port=8004"
#             - "--debug"
#             - "--log-config=uvicorn_config.json"
#           ports:
#             - containerPort: 8004
#           imagePullPolicy: Always
#           volumeMounts:
#             - mountPath: /files/share
#               name: data
#           env:
#             - name: MINIO_ACCESS_KEY
#               valueFrom:
#                 configMapKeyRef:
#                   name: atop-globe-config
#                   key: minio_access_key
#             - name: MINIO_HOST
#               valueFrom:
#                 configMapKeyRef:
#                   name: atop-globe-config
#                   key: minio_host
#             - name: MINIO_SECRET_KEY
#               valueFrom:
#                 configMapKeyRef:
#                   name: atop-globe-config
#                   key: minio_secret_key
#             - name: PORT
#               valueFrom:
#                 configMapKeyRef:
#                   name: atop-globe-config
#                   key: port
#             - name: HOST
#               valueFrom:
#                 configMapKeyRef:
#                   name: atop-globe-config
#                   key: host
#             - name: ENV
#               valueFrom:
#                 configMapKeyRef:
#                   name: atop-globe-config
#                   key: env
#         - name: http
#           image: "{{ .Values.registry }}/{{ .Values.repository }}/{{ .Values.image }}"
#           securityContext:
#             runAsUser: 0
#             privileged: false
#           command:
#             - "python"
#           args:
#             - "-m"
#             - "http.server"
#           ports:
#             - containerPort: 8000
#           imagePullPolicy: Always
#           volumeMounts:
#             - mountPath: /files/share
#               name: data
#   volumeClaimTemplates:
#     - metadata:
#         name: data
#       spec:
#         accessModes: ["ReadWriteOnce"]
#         resources:
#           requests:
#             storage: 20Gi
