import os


MIDDLEWARE_MINIO_SERVICE_HOST = os.getenv('MIDDLEWARE_MINIO_SERVICE_HOST')
MIDDLEWARE_MINIO_SERVICE_PORT = os.getenv('MIDDLEWARE_MINIO_SERVICE_PORT')
MIDDLEWARE_MINIO_ACCESS_KEY = os.getenv('MIDDLEWARE_MINIO_ACCESS_KEY')
MIDDLEWARE_MINIO_SECRET_KEY = os.getenv('MIDDLEWARE_MINIO_SECRET_KEY')